### ISSUE TITLE
Add a list of guessed words at the end of the challenge event.

### ISSUE THREAD

**Issue by dimiarbre** [ZeGmX/PiflouzBot#1]
For the subsequence challenge, we could make the bot write a message of all the used solutions (and by whom) once the event is finished.

**Comment by dimiarbre** [comment]
We could even give additional points to people that guessed a singular solution (e.g. no one guessed the same word as they did)

**Comment by ZeGmX** [comment]
I didn't link of the person who submitted the solutions, but I've implemented everything else

Announcing all submitted solutions: 0a4c6eb15f408d063de99ac4c717cb31825421cd
Announcing the number of possible solutions for each level: a0e858fcad99d0444c731bd25ae7f20e1479b044
Rewarding participants who submitted a unique solution: 3295f816119c0e1d14bb7574030bae9d4f32fb8e
