### ISSUE TITLE
Explicit chess error

### ISSUE THREAD

**Issue by dimiarbre** [ZeGmX/PiflouzBot#2]
Currently, the chess puzzle event only displays to the user "this move is incorrect" when a move does not match the expected move. However, this leads to issues:
- Once, my move went through, but I did not get an answer from Discord, so when I played the same move, I got "This move is incorrect," making me think it was not the right move.
- This may make the user not see a typo in their move, even though they had the right idea.

For those reasons, I'd like for the error message to be more explicit, at least detailing:
* if the move notation is malformed
* if the move is illegal in the current puzzle state
* if the move is not the correct one (legal, but not the solution)

**Comment by ZeGmX** [comment]
PR accepted (#3), issue fixed
